databases:
  - name: ai_translate_db
    region: singapore
    plan: free
    databaseName: ai_translate_db
    user: translate_user

services:
  - type: web
    name: AI-Translate
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn Multi-Translate-App.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: ai_translate_db
        fromDatabase:
          name: ai_translate_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true